### ISSUE TITLE
`ClassEnumVisitor` fails with anonymous class

### ISSUE THREAD

**Issue by marcosh** [phpmetrics/PhpMetrics#266]
If the analyzed code contains an anonymous class an error happens at line `42` of `ClassEnumVisitor` because `$node->namespacedName` is `null`.

**Comment by Fleshgrinder** [comment]
Just encountered the very same issue:

```
Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/src/Hal/Metric/Class_/ClassEnumVisitor.php on line 42

Fatal error: Uncaught Error: Call to a member function toString() on null in phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/src/Hal/Metric/Class_/ClassEnumVisitor.php:42
Stack trace:
#0 phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): Hal\Metric\Class_\ClassEnumVisitor->leaveNode(Object(PhpParser\Node\Stmt\Class_))
#1 phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(97): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\New_))
#2 phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(135): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ArrayItem))
#3 phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(84): PhpParser\NodeTraverser->traverseArray(Array)
#4 phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(97): PhpParse in phar://C:/Users/Fleshgrinder/bin/phpmetrics.phar/src/Hal/Metric/Class_/ClassEnumVisitor.php on line 42
```

**Comment by Halleck45** [comment]
Hi,

thanks for reporting the issue.

I'm not sure that's a PhpMetrics issue. Maybe it concerns the [PHP-Parser](https://github.com/nikic/PHP-Parser/issues).

I cannot reproduce. Can you provide an exemple of analyzed file please ?

**Comment by marcosh** [comment]
@Halleck45 I exposed the issue with a failing test in #271

**Comment by Halleck45** [comment]
Thank's ! Providing unit tests is a really good idea ! :+1:
