### ISSUE TITLE
`CyclomaticComplexityVisitor` fails with anonymous class

### ISSUE THREAD

**Issue by nyoro712** [phpmetrics/PhpMetrics#280]
Hi,

I've installed PhpMetrics 2.2.0 as phar archive.

When I analyzed a code contains an anonymous class, PhpMetrics failed.

Here is an example:

1. Create PHP code file named `test.php`

```php test.php
<?php
declare(strict_types=1);

namespace Foo;

class Bar
{
    public function getAnonymousClass()
    {
        return new class {};
    }
}

```
2. Run `phpmetrics --report-html="report" test.php` command in the directory where `test.php` exists.
3. I get this output:

```
[2K... 100% ...PHP Notice:  Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php on line 50

Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php on line 50
PHP Fatal error:  Uncaught Error: Call to a member function toString() on null in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php:50
Stack trace:
#0 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(127): Hal\Metric\Class_\Complexity\CyclomaticComplexityVisitor->leaveNode(Object(PhpParser\Node\Stmt\Class_))
#1 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(120): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\New_))
#2 phar://D:/php/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php(60): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#3 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): Hal\Component\Ast\NodeTraverser->traverseArray(Array)
#4 phar://D:/php/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php(60): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 phar://D:/php/phpmetrics/vendor/nikic/php-parser/li in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php on line 50

Fatal error: Uncaught Error: Call to a member function toString() on null in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php:50
Stack trace:
#0 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(127): Hal\Metric\Class_\Complexity\CyclomaticComplexityVisitor->leaveNode(Object(PhpParser\Node\Stmt\Class_))
#1 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(120): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\New_))
#2 phar://D:/php/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php(60): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#3 phar://D:/php/phpmetrics/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): Hal\Component\Ast\NodeTraverser->traverseArray(Array)
#4 phar://D:/php/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php(60): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 phar://D:/php/phpmetrics/vendor/nikic/php-parser/li in phar://D:/php/phpmetrics/src/Hal/Metric/Class_/Complexity/CyclomaticComplexityVisitor.php on line 50
```

4. Modify `test.php` and comment out the anonymous class like this:

```diff
  class Bar
  {
      public function getAnonymousClass()
      {
-         return new class {};
+ //        return new class {};
      }
  }
```

5. Run `phpmetrics --report-html="report" test.php` again.
6. The report generated and I get this output:

```
[2K... 100% ...

[2KExecuting system analyzes...

[2KLOC
    Lines of code                               8
    Logical lines of code                       7
    Comment lines of code                       1
    Average volume                              0
    Average comment weight                      13.02
    Average intelligent content                 13.02
    Logical lines of code by class              7
    Logical lines of code by method             7

Object oriented programming
    Classes                                     1
    Interface                                   0
    Methods                                     1
    Methods by class                            1
    Lack of cohesion of methods                 0.5
    Average afferent coupling                   0
    Average efferent coupling                   0
    Average instability                         0

Complexity
    Average Cyclomatic complexity by class      0.67
    Average Relative system complexity          0
    Average Difficulty                          0

Bugs
    Average bugs by class                       0
    Average defects by class (Kan)              0.08

Violations
    Critical                                    0
    Error                                       0
    Warning                                     0
    Information                                 0



HTML report generated in "report" directory

Done
```

**Comment by FractalizeR** [comment]
This is because of this code:
```
    /*
     * @inheritdoc
     */
    public function leaveNode(Node $node)
    {
        if ($node instanceof Stmt\Class_
            || $node instanceof Stmt\Interface_
        ) {

            $class = $this->metrics->get($node->namespacedName->toString());
```

```$node->namespacedName``` property is absent at anonymous classes.

**Comment by FractalizeR** [comment]
I've provided a PR with a fix for this issue and some unit tests.

**Comment by garex** [comment]
What do we waiting for? When it will be hotfixed/released at packagist?

**Comment by niconoe-** [comment]
Soon, I have other stuff to add in the new release that are not fully ready yet.
But the 2.3.0 will be released very soon. I'm working at.
